### ISSUE TITLE
IOError 

### ISSUE THREAD

**Issue by tansaku** [colszowka/simplecov-html#41]
I'm getting an odd IOError when running simplecov with feature tests, but not just on specs:

``` sh
/Users/tansaku/.rvm/gems/ruby-2.2.2/gems/simplecov-html-0.9.0/lib/simplecov-html.rb:21:in `write': not opened for writing (IOError)
    from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/simplecov-html-0.9.0/lib/simplecov-html.rb:21:in `puts'
    from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/simplecov-html-0.9.0/lib/simplecov-html.rb:21:in `puts'
    from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/simplecov-html-0.9.0/lib/simplecov-html.rb:21:in `format'
    from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/simplecov-0.9.2/lib/simplecov/result.rb:46:in `format!'
    from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/simplecov-0.9.2/lib/simplecov/configuration.rb:158:in `block in at_exit'
    from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/simplecov-0.9.2/lib/simplecov/defaults.rb:54:in `call'
    from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/simplecov-0.9.2/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
```

Our project has features in a features directory, straight off the root, and specs in a spec directory also straight off root.  I get the above running "rspec features" but don't get it when running "rspec" or "rspec spec".

Everything still seems to work in terms of the simplecov output, but gets this error thrown as well ...

**Comment by tansaku** [comment]
I tried upgrading simplecov to the latest version, but same issue:

```sh
/Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `write': not opened for writing (IOError)
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `puts'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `puts'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `format'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-0.10.0/lib/simplecov/result.rb:46:in `format!'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-0.10.0/lib/simplecov/configuration.rb:159:in `block in at_exit'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `call'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `block in <top (required)>'
```

**Comment by tansaku** [comment]
I also tried moving the feature folder into the spec folder, but again same error

**Comment by tansaku** [comment]
and I still get it from running a single feature

```sh
→ rspec features/login_spec.rb 

Logging in and out
  logged in
  logout

Finished in 0.29282 seconds (files took 1 second to load)
2 examples, 0 failures
/Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `write': not opened for writing (IOError)
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `puts'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `puts'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `format'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-0.10.0/lib/simplecov/result.rb:46:in `format!'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-0.10.0/lib/simplecov/configuration.rb:159:in `block in at_exit'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `call'
	from /Users/tansaku/.rvm/gems/ruby-2.0.0-p598/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `block in <top (required)>'
```

**Comment by tansaku** [comment]
I can totally imagine that this is due to something weird in our setup - just wondering if anyone else has ever seen the same ...

**Comment by colszowka** [comment]
This should not be related to the location of your spec/feature folders, it seems simplecov is failing to write it's coverage report. Can you try to delete the `./coverage` directory and try again?

**Comment by tansaku** [comment]
ah, I think we just worked out it is because we are using webmock with the features, which prevents simplecov from outputing the message to the console:

```ruby
        puts output_message(result)
      end

      def output_message(result)
        "Coverage report generated for #{result.command_name} to #{output_path}. #{result.covered_lines} / #{result.total_lines} LOC (#{result.covered_percent.round(2)}%) covered."
      end
```

**Comment by colszowka** [comment]
That is awkward, webmock should not be related to $stdout output and I have used it on many projects along simplecov without problems. But maybe you are somewhere else closing/redirecting $stdout/STDOUT?

**Comment by PragTob** [comment]
Closing due to inactivity and seemingly/hopefully not related to simplecov itself.
